[build-system]
# We replace setuptools with scikit-build-core
requires = ["scikit-build-core>=0.10.0"]
build-backend = "scikit_build_core.build"

[project]
name = "hypergl"
version = "2.1.0"
description = "High Performance, Modernized OpenGL wrapper"
readme = "README.md"
authors = [{name = "Mai Huy Hiếu"}]
license = { text = "MIT" }
# Matches your 3.13+ free-threading requirement
requires-python = ">=3.13" 
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Multimedia :: Graphics",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]

# --- Scikit-Build-Core Configuration ---
[tool.scikit-build]
wheel.install-dir = "hypergl"
wheel.exclude = [
    "culverin/include/**",
    "culverin/lib/**",
    "culverin/share/**",
    "src/**",
    "**/*.c",
    "**/*.h",
    "**/*.cpp",
    "**/*.obj",
    "**/*.a",
    "**/*.lib",
    "**/*.pdb"
]

cmake.args = [
    "-DCMAKE_C_STANDARD=23",
    "-DCMAKE_C_EXTENSIONS=ON",
    "-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON",
    # Force Clang-cl or Clang as the compiler
    "-GNinja",
    "-DCMAKE_C_COMPILER=clang-cl", 
    "-DCMAKE_CXX_COMPILER=clang-cl"
]   

[tool.isort]
line_length = 120
multi_line_output = 5
include_trailing_comma = true
known_first_party = ["hypergl"]

[tool.scikit-build.sdist]
include = ["culverin/*.pyi", "extern/**", "src/**"]
exclude = ["build/**", "dist/**"]